// proxy-server.js
const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');

const app = express();
app.use(cors());
app.use(express.json());

const PORT = 18790;
const STATUS_FILE = path.join(__dirname, '.cursor-stream-status.json');

let streamState = {
    isStreaming: false,
    currentFile: '',
    currentContent: '',
    startTime: null,
    chunks: []
};

function writeStatus() {
    fs.writeFileSync(STATUS_FILE, JSON.stringify({
        ...streamState,
        timestamp: Date.now()
    }, null, 2));
}

function notifyExtension(event, data = {}) {
    const update = {
        event,
        ...streamState,
        ...data,
        timestamp: Date.now()
    };
    fs.writeFileSync(STATUS_FILE, JSON.stringify(update, null, 2));
    console.log(`[Notify] ${event}:`, data.filePath || (data.chunk ? data.chunk.slice(0, 50) : ''));
}

// 模拟流式输出
function startMockStream(filePath, prompt) {
    streamState.isStreaming = true;
    streamState.currentFile = filePath;
    streamState.currentContent = '';
    streamState.startTime = Date.now();
    streamState.chunks = [];
    writeStatus();
    notifyExtension('start', { filePath });

    const mockCode = `
// AI 正在生成: ${path.basename(filePath)}
// 根据 prompt: "${prompt.slice(0, 80)}..."

function ${path.basename(filePath, '.js').replace(/[^a-zA-Z]/g, '_')}() {
    console.log("Hello from Cursor AI!");
    return {
        status: "success",
        message: "File generated by AI"
    };
}

export default ${path.basename(filePath, '.js').replace(/[^a-zA-Z]/g, '_')};
`.trim();

    let index = 0;
    const interval = setInterval(() => {
        if (index < mockCode.length) {
            const chunk = mockCode[index];
            streamState.currentContent += chunk;
            streamState.chunks.push(chunk);
            writeStatus();
            notifyExtension('chunk', { chunk });
            index++;
        } else {
            clearInterval(interval);
            streamState.isStreaming = false;
            writeStatus();
            notifyExtension('end');
            console.log('[Stream] 完成');
        }
    }, 20);
}

// API 端点
app.post('/v1/chat/completions', (req, res) => {
    const { messages, stream = true } = req.body;
    const lastMessage = messages[messages.length - 1]?.content || '';
    
    let filePath = 'unknown.js';
    const fileMatch = lastMessage.match(/[\/\w\-\.]+\.\w+/);
    if (fileMatch) filePath = fileMatch[0];
    
    console.log(`[API] 收到请求: ${lastMessage.slice(0, 100)}`);
    
    if (stream) {
        res.setHeader('Content-Type', 'text/event-stream');
        res.setHeader('Cache-Control', 'no-cache');
        res.setHeader('Connection', 'keep-alive');
        
        startMockStream(filePath, lastMessage);
        
        // 发送 SSE 响应
        const sendChunk = () => {
            if (streamState.isStreaming) {
                const chunk = streamState.chunks[streamState.chunks.length - 1] || '';
                res.write(`data: ${JSON.stringify({ choices: [{ delta: { content: chunk } }] })}\n\n`);
                setTimeout(sendChunk, 50);
            } else {
                res.write('data: [DONE]\n\n');
                res.end();
            }
        };
        sendChunk();
    } else {
        res.json({ choices: [{ message: { content: 'Mock response' } }] });
    }
});

app.listen(PORT, () => {
    console.log(`\n🚀 Cursor Stream Proxy 已启动`);
    console.log(`📡 监听端口: ${PORT}`);
    console.log(`📁 状态文件: ${STATUS_FILE}\n`);
});